config/routes.rb
Rails.application.routes.draw do

  root 'images#index'
  resources :images

  devise_for :users
  resource :images
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  # belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :rememberable, :trackable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.order(created_at: :desc)
  end


  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>All comments</h1>
<div class="row">
  <div class="col-sm-4">
    <% @comments.each do |comment| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= comment.grade %>
            <h4><%= comment.comment %></h4>
            <p>by: <%= link_to comment.user.name, '#' %></p>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1><%= @comment.name %></h1>

<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div class="panel-body">
        <% User.all.each do |user| %>
            <li><%= link_to user.name, '#' %>
        <% end %>
      </div>
    </div>

  </div>
  <div class="col-sm-6">
    <% @comments.each do |comment| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <p>grade: <%= comment.grade %></p>
            <h4><%= link_to comment.comment, comment_path(comment) %></h4>
            <p>by: <%= comment.user.name %></p>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<h1>All images</h1>
<div class="row">
  <div class="col-sm-4">
    <% @images.each do |image| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to image.image, image_path(image) %>
            <h4><%= link_to image.title, image_path(image) %></h4>
            <p>by: <%= link_to image.user.name, image_path(image) %></p>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/images/new.html.erb
<h1>Create image</h1>
<%= form_for @image do |f| %>
    <div class="form-group">
      <%= f.label :user %><br />
      <%= f.collection_select :User_id, User.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image %><br />
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :user %><br />
      <%= f.collection_select :User_id, User.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/images/show.html.erb
<%= link_to 'List of all images', root_path %> > <%= @notice.title %>
<h1><%= @image.title %></h1>
<p>
  User: <%= link_to @image.user.name, '#' %>, by: <%= notice.user.name %>
</p>
<p>
  <%= image_tag @image.url(:thumb) %>


</p>
<p>
  <b>comments:</b><br/>
<div class="row">
  <div class="col-sm-4">
    <% Comment.all.each do |comment| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= comment.grade %>
            <h4><%= comment.comment %></h4>

            <p>by: <%= link_to comment.user.name, '#' %></p>
          </div>
        </div>
    <% end %>

  </div>
</div>
</p>
<p>
  <% if current_user == @image.user %>
      <%= link_to "Edit notice", edit_image_path, class: 'btn btn-primary' %>
      <%= link_to "Delete notice", image_path(@image), method: :delete, class: 'btn btn-danger' %>
  <%= end %>
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Photo Gallery', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <li class="navbar-text">Hello, <%= current.user.name %></li>
              <li><%= link_to 'Create image', new_image_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>

        <%= link_to 'Register', new_user_registration_path,  class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Log in', new_user_session_path,  class: 'btn btn-default navbar-btn' %>
            <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>" role="alert"><%= message %></div>
  <% end %>


  <%= yield %>
</div>

</body>
</html>